name: driver_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl_phone_field: ^3.2.0
  image_picker: ^1.2.0
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.10.0
  dotted_border: ^2.0.0
  table_calendar: ^3.0.9
  flutter_lucide: ^1.7.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.12.0
  csc_picker: ^0.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # ✅ fixed path

#
#flutter_native_splash:
#  color: "#FFFFFF"
#  image: "assets/images/app_logo.png"
#  android: true
#  ios: true
#  web: false
#  fullscreen: true
#  android_gravity: center

